name: Build on pull request to master

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Install NPM dependencies
        run: npm install
      - name: Call linter
        run: npm run lint
      - name: Build code
        env:
          NODE_OPTIONS: '--max-old-space-size=8192'
        run: npm run build
